using System;
using System.Collections.Generic;

namespace StockExchange.Business.Models.Indicators
{
    /// <summary>
    /// Contains information about a signal generated by a technical
    /// indicator
    /// </summary>
    public class SignalEvent
    {
        /// <summary>
        /// Date when the signal was generated
        /// </summary>
        public DateTime Date { get; set; }
        
        /// <summary>
        /// Companies which stocks should be sold on that day
        /// </summary>
        public IList<int> CompaniesToSell { get; set; }

        /// <summary>
        /// Companies which stocks should be bought on that day
        /// </summary>
        public IList<int> CompaniesToBuy { get; set; }
    }
}
