insert into dbo.Company values
	('kgh', N'KGHM Polska Miedź SA (KGH)'),
	('acp', N'Asseco Poland SA (ACP)'),
	('alr', N'Alior Bank SA (ALR)'),
	('bzw', N'Bank Zachodni WBK SA (BZW)'),
	('ccc', N'CCC SA (CCC)'),
	('cps', N'Cyfrowy Polsat SA (CPS)'),
	('ena', N'Enea SA (ENA)'),
	('eng', N'Energa SA (ENG)'),
	('eur', N'Eurocash SA (EUR)'),
	('lpp', N'LPP SA (LPP)'),
	('lts', N'Grupa Lotos SA (LTS)'),
	('mbk', N'mBank SA (MBK)'),
	('opl', N'Orange Polska SA (OPL)'),
	('peo', N'Bank Polska Kasa Opieki SA (PEO)'),
	('pge', N'PGE Polska Grupa Energetyczna SA (PGE)'),
	('pgn', N'Polskie Górnictwo Naftowe i Gazownictwo SA (PGN)'),
	('pkn', N'Polski Koncern Naftowy ORLEN SA (PKN)'),
	('pko', N'Powszechna Kasa Oszczędności Bank Polski SA (PKO)'),
	('pzu', N'Powszechny Zakład Ubezpieczeń SA (PZU)'),
	('tpe', N'Tauron Polska Energia SA (TPE)');