//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockExchange.Business.Indicators.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IndicatorDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndicatorDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockExchange.Business.Indicators.Common.IndicatorDescriptions", typeof(IndicatorDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when +DI line crosses above -DI line and ADX value is greater than 25..
        /// </summary>
        internal static string AdxBuySignal {
            get {
                return ResourceManager.GetString("AdxBuySignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when +DI line crosses below -DI line and ADX value is greater than 25..
        /// </summary>
        internal static string AdxSellSignal {
            get {
                return ResourceManager.GetString("AdxSellSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when current close price is greater than the sum of previous close price and ATR indicator value for previous day..
        /// </summary>
        internal static string AtrBuySignal {
            get {
                return ResourceManager.GetString("AtrBuySignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when current close price is less than the difference of previous close price and ATR value for previous day..
        /// </summary>
        internal static string AtrSellSignal {
            get {
                return ResourceManager.GetString("AtrSellSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when current close price is greater than EMA value and average values are growing..
        /// </summary>
        internal static string EmaBuySignal {
            get {
                return ResourceManager.GetString("EmaBuySignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when current close price is less than EMA value and average values are falling..
        /// </summary>
        internal static string EmaSellSignal {
            get {
                return ResourceManager.GetString("EmaSellSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when MACD line crosses above signal line..
        /// </summary>
        internal static string MacdBuySignal {
            get {
                return ResourceManager.GetString("MacdBuySignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when MACD line crosses below signal line..
        /// </summary>
        internal static string MacdSellSignal {
            get {
                return ResourceManager.GetString("MacdSellSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when current close price is greater than the second resistance level..
        /// </summary>
        internal static string PpBuySignal {
            get {
                return ResourceManager.GetString("PpBuySignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when current close price is greater than the second support level..
        /// </summary>
        internal static string PpSellSignal {
            get {
                return ResourceManager.GetString("PpSellSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when ROC values are negative and prices trend values are growing..
        /// </summary>
        internal static string RocBuySignal {
            get {
                return ResourceManager.GetString("RocBuySignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when ROC values are positive and prices trend values are falling..
        /// </summary>
        internal static string RocSellSignal {
            get {
                return ResourceManager.GetString("RocSellSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when RSI indicator value crosses above Minimum property value..
        /// </summary>
        internal static string RsiBuySignal {
            get {
                return ResourceManager.GetString("RsiBuySignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when RSI indicator value crosses below Maximum property value..
        /// </summary>
        internal static string RsiSellSignal {
            get {
                return ResourceManager.GetString("RsiSellSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when current close price is greater than SMA value and average values are growing..
        /// </summary>
        internal static string SmaBuySignal {
            get {
                return ResourceManager.GetString("SmaBuySignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when current close price is less than SMA value and average values are falling..
        /// </summary>
        internal static string SmaSellSignal {
            get {
                return ResourceManager.GetString("SmaSellSignal", resourceCulture);
            }
        }
    }
}
